# Random Forest Notebook
Attempting to implement random forrest algorithm for research and performance
https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html
https://data36.com/random-forest-in-python/

### Todo:
Understand and improve RF Model
Implement vectorisation model
Abstract data processing and filtering/wrangling to function

In [67]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier as rfc
from sklearn.metrics import mean_squared_error
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
import statistics as stats
import time

In [2]:
# Removes warnings for the error messege
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
# Make sparse coulms, fix everything
# Scale the data for svm

In [3]:
X_full_train = pd.read_csv(r"book_rating_train.csv", index_col = False, delimiter = ',', header=0)
X_train = X_full_train.iloc[:,:-1]
Y_train = X_full_train["rating_label"]

In [4]:
doc2vec_data_source = "book_text_features_doc2vec"
# Maybe replace names of 0, 1, 2 etc with word vector i
# can't do random forrest with float64, need int64
authors_d2v_test = pd.read_csv(f"{doc2vec_data_source}/test_authors_doc2vec20.csv", index_col = False, delimiter = ',', header=None)
authors_d2v_train = pd.read_csv(f"{doc2vec_data_source}/train_authors_doc2vec20.csv", index_col = False, delimiter = ',', header=None)

desc_d2v_test = pd.read_csv(f"{doc2vec_data_source}/test_desc_doc2vec100.csv", index_col = False, delimiter = ',', header=None)
desc_d2v_train = pd.read_csv(f"{doc2vec_data_source}/train_desc_doc2vec100.csv", index_col = False, delimiter = ',', header=None)

name_d2v_test = pd.read_csv(f"{doc2vec_data_source}/test_name_doc2vec100.csv", index_col = False, delimiter = ',', header=None)
name_d2v_train = pd.read_csv(f"{doc2vec_data_source}/train_name_doc2vec100.csv", index_col = False, delimiter = ',', header=None)

In [5]:
# Gets the data types, and removes all int data types
# X_string = X.select_dtypes(exclude="number")
X_train_numerical = X_train.select_dtypes(include="number")

In [69]:
def showMetrics(y_true, y_pred):
    # print the metrics
    print("Accuracy: {:.3f}".format(accuracy_score(y_true, y_pred)))
    print("Precision: {:.3f}".format(precision_score(y_true, y_pred, average='macro', zero_division=0)))
    print("Recall: {:.3f}".format(recall_score(y_true, y_pred, average='macro')))
    print("F1: {:.3f}".format(f1_score(y_true, y_pred, average='macro')))
    # print("Confusion Matrix:")
    # cm = confusion_matrix(y_true, y_pred)
    # sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
    # plt.show()

In [70]:
def randomForest(x_train=None, x_test=None, y_train=None, y_test=None, num_trees=100, depth=2, state=0):
    clf = rfc(n_estimators=num_trees, max_depth=depth, random_state=state)
    clf.fit(x_train, y_train)

    predictions = clf.predict(x_test)
    print(f"Max: {max(predictions)}, Min: {min(predictions)}, Mode: {stats.mode(predictions)}")
    # print(predictions)
    

    describe_data = pd.DataFrame(predictions)
    # print(describe_data.describe())
    showMetrics(y_test, predictions)
    # accuracy = accuracy_score(y_test, predictions)
    # print(accuracy)
    
    return clf

In [8]:
# Merging all data together
# doc2vec
start_time = time.time()

X_train_merged = pd.concat([X_train_numerical, authors_d2v_train, desc_d2v_train, name_d2v_train], axis=1)

end_time = time.time()
elapsed_time = end_time - start_time
print(f"Time taken to run: {elapsed_time:.4f} seconds")
X_train_merged

Time taken to run: 0.0160 seconds

,PublishYear,PublishMonth,PublishDay,pagesNumber,0,1,2,3,4,5,...,90,91,92,93,94,95,96,97,98,99
0,2005,6,1,48,0.359375,-0.096944,0.021326,0.304888,-0.084434,-0.138658,...,-0.172811,0.098389,-0.062941,0.118057,-0.065377,0.227973,0.218879,-0.151266,-0.048105,0.300822
1,1991,10,1,364,-0.074845,0.060063,0.132891,0.051957,0.127083,0.017997,...,0.245650,-0.049657,0.072740,-0.055925,-0.000046,0.140500,0.067133,-0.238091,0.109774,-0.156772
2,2005,3,31,32,-0.127589,-0.100911,0.158580,0.046532,-0.065661,-0.037972,...,-0.033781,0.093943,0.132654,0.030295,0.102714,0.154334,0.129325,-0.231493,0.007541,-0.098540
3,2004,9,1,293,-0.000472,-0.048197,0.106046,-0.100795,-0.147681,-0.017288,...,0.020762,-0.149720,0.150557,0.294355,0.001157,0.285179,0.049340,-0.037548,0.042920,0.176173
4,2005,7,7,352,-0.162106,-0.023212,0.189444,-0.042658,-0.117135,-0.075968,...,0.191644,0.044182,0.054631,-0.025782,0.049917,0.122052,-0.084216,-0.096424,-0.068681,-0.005293
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23058,1997,8,1,120,-0.194677,0.063026,0.125115,-0.041354,-0.122502,-0.207333,...,-0.000418,-0.062899,0.048064,0.029612,0.191065,0.096081,-0.100516,-0.190299,0.224559,0.086601
23059,2005,6,1,32,-0.115993,-0.003955,-0.027285,-0.032830,0.091905,-0.257285,...,0.150964,-0.029046,0.171029,-0.072123,-0.004459,0.247430,0.111973,0.019573,0.070569,-0.112066
23060,1989,2,15,132,-0.126878,-0.120418,0.198828,0.093403,-0.053232,-0.114909,...,0.193755,-0.118570,0.006740,-0.108623,-0.036143,0.168113,0.136478,0.087885,0.113180,0.000569
23061,1998,4,21,136,-0.134530,-0.061256,0.178935,0.057537,-0.045066,-0.088796,...,0.009007,0.154127,0.219128,-0.305824,-0.017904,-0.059886,0.108616,0.041879,-0.138893,-0.044187
23062,2002,7,8,192,-0.204117,-0.007189,0.375681,0.011292,-0.341423,-0.061017,...,0.068714,-0.065924,0.082228,-0.003849,0.099006,0.081608,0.094459,-0.048776,0.032433,0.132977

In [10]:
X_train_numerical.shape, authors_d2v_train.shape, desc_d2v_train.shape, name_d2v_train.shape

((23063, 4), (23063, 20), (23063, 100), (23063, 100))

In [78]:
X_train, X_test, y_train, y_test = train_test_split(X_train_merged, Y_train, test_size=0.2, random_state=42)

start_time = time.time()
randomForest(X_train, X_test, y_train, y_test, 200, 4)
end_time = time.time()
print(f"Time: {end_time - start_time:.2f}")

Max: 4.0, Min: 4.0, Mode: 4.0
Accuracy: 0.711
Precision: 0.237
Recall: 0.333
F1: 0.277
Time: 45.51

In [12]:
Y_test = pd.read_csv(r"book_rating_test.csv", index_col = False, delimiter = ',', header=0)

In [13]:
16208 / Y_train.shape[0]

0.7027706716385552

In [14]:
rf_data = pd.read_csv(r"RF_accuracy_scores.csv", index_col = False, delimiter = ',', header=0)

In [15]:
rf_data.max().max()

19.0

In [ ]:
# y_test.shape
data = np.full((2020,), 4)
df = pd.DataFrame(data)
accuracy_score(y_test, df)

In [18]:
Y_train.value_counts()

4.0    16208
3.0     5864
5.0      991
Name: rating_label, dtype: int64

In [52]:
testing_data = pd.read_csv(r"book_rating_test.csv", index_col = False, delimiter = ',', header=0)
testing_data = testing_data.select_dtypes(include="number")
data = pd.concat([testing_data, authors_d2v_test, desc_d2v_test, name_d2v_test], axis=1)
# Remove the first column id
data = data.iloc[:, 1:]

In [47]:
def randomForest_test(x_train=None, x_test=None, y_train=None, y_test=None, num_trees=100, depth=2, state=0):
    clf = rfc(n_estimators=num_trees, max_depth=depth, random_state=state)
    clf.fit(x_train, y_train)

    predictions = clf.predict(x_test)
    predictions_df = pd.DataFrame(predictions)
    # print(f"Max: {max(predictions)}, Min: {min(predictions)}, Mode: {stats.mode(predictions)}")
    # print(predictions)
    

    describe_data = pd.DataFrame(predictions)
    print(describe_data.describe())
    
    return predictions_df

In [54]:
output = randomForest_test(x_train=X_train, x_test=data, y_train=y_train)

            0
count  5766.0
mean      4.0
std       0.0
min       4.0
25%       4.0
50%       4.0
75%       4.0
max       4.0

        0
0     4.0
1     4.0
2     4.0
3     4.0
4     4.0
...   ...
5761  4.0
5762  4.0
5763  4.0
5764  4.0
5765  4.0

[5766 rows x 1 columns]

In [63]:
output.index = np.arange(1, len(output)+1)
output.to_csv("predictions.csv", header=["rating_label"], index_label="id")
output

        0
1     4.0
2     4.0
3     4.0
4     4.0
5     4.0
...   ...
5762  4.0
5763  4.0
5764  4.0
5765  4.0
5766  4.0

[5766 rows x 1 columns]